const LOADING_CONTRIBUTIONS = 'LOADING_CONTRIBUTIONS';
const SUCCESS_CONTRIBUTIONS = 'SUCCESS_CONTRIBUTIONS';
const ERROR_CONTRIBUTIONS = 'ERROR_CONTRIBUTIONS';

export { LOADING_CONTRIBUTIONS, SUCCESS_CONTRIBUTIONS, ERROR_CONTRIBUTIONS };
