const LOADING_SEARCH_RESULTS = 'LOADING_SEARCH_RESULTS';
const SUCCESS_SEARCH = 'SUCCESS_SEARCH';
const ERROR_SEARCH = 'ERROR_SEARCH';
export {
  LOADING_SEARCH_RESULTS,
  SUCCESS_SEARCH,
  ERROR_SEARCH,
};
