const LOADING_RECEIVED_EVENTS = 'LOADING_RECEIVED_EVENTS';
const SUCCESS_RECEIVED_EVENTS = 'SUCCESS_RECEIVED_EVENTS';
const ERROR_RECEIVED_EVENTS = 'ERROR_RECEIVED_EVENTS';

export {   LOADING_RECEIVED_EVENTS,
    SUCCESS_RECEIVED_EVENTS,
    ERROR_RECEIVED_EVENTS,
   };
