const FAILED_LOGIN = 'FAILED_LOGIN';
const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
const ERORR_LOGIN = 'ERORR_LOGIN';
const LOADING_LOGIN = 'LOADING_LOGIN';

export {
  FAILED_LOGIN, SUCCESSFUL_LOGIN, ERORR_LOGIN, LOADING_LOGIN,
};
