const LOADING_USER_EVENTS = 'LOADING_USER_EVENTS';
const SUCCESS_USER_EVENTS = 'SUCCESS_USER_EVENTS';
const ERROR_USER_EVENTS = 'ERROR_USER_EVENTS';

export { LOADING_USER_EVENTS, SUCCESS_USER_EVENTS, ERROR_USER_EVENTS };
